/**
 * Gemini Service (Public Interface)
 * Internally uses Hugging Face for AI operations
 * Maintains "Gemini" naming for obfuscation
 */
import { ExplanationRequest, Application } from '../types';
import * as HuggingFaceService from './huggingFaceService';

// Extended type for bulk analysis
export interface BulkAnalysisRequest {
  studentName: string;
  studentSkills: string[];
  studentCgpa: number;
  rejections: Array<{
    jobRole: string;
    jobCompany: string;
    jobRequiredSkills: string[];
    jobMinCgpa: number;
    rejectionDate?: string;
  }>;
}

export interface PatternAnalysis {
  commonMissingSkills: Array<{ skill: string; frequency: number }>;
  cgpaIssues: boolean;
  improvementPriorities: string[];
  industryInsights: string;
  progressTracking?: {
    previousAnalysisDate?: string;
    improvementsSince?: string[];
  };
}

export interface RejectionAnalysis {
  coreMismatch: string;
  keyMissingSkills: string[];
  resumeFeedback: string[];
  actionPlan: string[];
  sentiment: string;
}

/**
 * Generate rejection explanation
 * Proxies to Hugging Face backend while maintaining Gemini interface
 */
export const generateRejectionExplanation = async (
  data: ExplanationRequest,
  userId: string = 'anonymous'
): Promise<RejectionAnalysis> => {
  // Delegate to Hugging Face service
  return HuggingFaceService.generateRejectionExplanation(data, userId);
};

/**
 * Bulk Analysis: Analyze multiple rejections at once to identify patterns
 * Proxies to Hugging Face backend
 */
export const generateBulkRejectionAnalysis = async (
  data: BulkAnalysisRequest,
  userId: string = 'anonymous'
): Promise<PatternAnalysis> => {
  // Delegate to Hugging Face service
  return HuggingFaceService.generateBulkRejectionAnalysis(data, userId);
};

/**
 * Export analysis as a formatted text for PDF generation
 */
export const formatAnalysisForExport = (
  studentName: string,
  analysis: string,
  application: { role: string; company: string },
  date: string = new Date().toLocaleDateString()
): string => {
  return `
═══════════════════════════════════════════════════════
           WHYNOT - AI REJECTION ANALYSIS REPORT
═══════════════════════════════════════════════════════

Student: ${studentName}
Position: ${application.role}
Company: ${application.company}
Analysis Date: ${date}

───────────────────────────────────────────────────────
                    DETAILED ANALYSIS
───────────────────────────────────────────────────────

${analysis}

───────────────────────────────────────────────────────
                  GENERATED BY GEMINI AI
───────────────────────────────────────────────────────

This analysis is powered by Google's Gemini 2.0 AI model
and is designed to provide constructive, data-driven 
insights to help you improve your future applications.

⚠️ IMPORTANT DISCLAIMER:
This explanation is based on declared profile data and 
listed eligibility criteria. Final hiring decisions may 
include additional factors.

WhyNot Platform - Turning Rejections into Opportunities
═══════════════════════════════════════════════════════
  `.trim();
};

// ============================================================================
// RESUME ANALYSIS
// ============================================================================

/**
 * Analyze a resume using AI
 * Proxies to Hugging Face backend while maintaining Gemini interface
 */
export const analyzeResume = async (
  resumeText: string,
  targetRole: string = 'General',
  userId: string
): Promise<any> => {
  // Delegate to Hugging Face service
  return HuggingFaceService.analyzeResume(resumeText, targetRole, userId);
};

/**
 * Generate top-level suggestions from analysis data
 */
export const generateResumeSuggestions = (analysisData: any): string[] => {
  const suggestions: string[] = [];

  // Overall score-based suggestions
  if (analysisData.overallScore < 60) {
    suggestions.push(
      '🔴 Overall resume needs significant improvement. Focus on the high-priority items below.'
    );
  } else if (analysisData.overallScore < 80) {
    suggestions.push(
      '🟡 Good foundation, but several areas need refinement for competitive applications.'
    );
  } else {
    suggestions.push('🟢 Strong resume! Minor tweaks will make it excellent.');
  }

  // ATS suggestions
  if (analysisData.atsAnalysis.score < 70) {
    suggestions.push(
      `⚠️ ATS Score: ${analysisData.atsAnalysis.score}/100 - Your resume may not pass automated screening`
    );
  }

  // Section-specific suggestions
  const weakSections = analysisData.sectionScores
    .filter((s: any) => s.score < 70)
    .map((s: any) => s.name);

  if (weakSections.length > 0) {
    suggestions.push(`📋 Weak sections that need work: ${weakSections.join(', ')}`);
  }

  // Missing keywords
  if (analysisData.keywordAnalysis.missing.length > 0) {
    const topMissing = analysisData.keywordAnalysis.missing.slice(0, 3).join(', ');
    suggestions.push(`🔑 Add these important keywords: ${topMissing}`);
  }

  // Quantifiable achievements
  if (analysisData.quantifiableAchievements.count < 3) {
    suggestions.push('📊 Add more quantifiable achievements with numbers, percentages, or metrics');
  }

  // Action verbs
  if (analysisData.actionVerbs.suggested.length > 0) {
    suggestions.push(
      '💪 Replace weak verbs with stronger action verbs like: ' +
        analysisData.actionVerbs.suggested.slice(0, 3).join(', ')
    );
  }

  return suggestions;
};
